# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tasks_Tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tasks_Tab(object):
    def setupUi(self, Tasks_Tab):
        Tasks_Tab.setObjectName("Tasks_Tab")
        Tasks_Tab.resize(800, 600)
        self.listView = QtWidgets.QListView(Tasks_Tab)
        self.listView.setGeometry(QtCore.QRect(0, 40, 191, 561))
        self.listView.setObjectName("listView")
        self.widget = QtWidgets.QWidget(Tasks_Tab)
        self.widget.setGeometry(QtCore.QRect(360, 70, 431, 42))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(Tasks_Tab)
        QtCore.QMetaObject.connectSlotsByName(Tasks_Tab)

    def retranslateUi(self, Tasks_Tab):
        _translate = QtCore.QCoreApplication.translate
        Tasks_Tab.setWindowTitle(_translate("Tasks_Tab", "Tasks_Tab"))
        self.pushButton.setText(_translate("Tasks_Tab", "PushButton"))
        self.pushButton_2.setText(_translate("Tasks_Tab", "PushButton"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tasks_Tab = QtWidgets.QWidget()
    ui = Ui_Tasks_Tab()
    ui.setupUi(Tasks_Tab)
    Tasks_Tab.show()
    sys.exit(app.exec_())
