# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tasks_Tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Tasks_Tab(object):
    def setupUi(self, Tasks_Tab):
        Tasks_Tab.setObjectName("Tasks_Tab")
        Tasks_Tab.resize(700, 506)
        Tasks_Tab.setMinimumSize(QtCore.QSize(700, 506))
        Tasks_Tab.setMaximumSize(QtCore.QSize(700, 506))
        self.widget = QtWidgets.QWidget(Tasks_Tab)
        self.widget.setGeometry(QtCore.QRect(140, 50, 271, 42))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.board_name_edit = QtWidgets.QLineEdit(self.widget)
        self.board_name_edit.setObjectName("board_name_edit")
        self.horizontalLayout.addWidget(self.board_name_edit)
        self.board_add_button = QtWidgets.QPushButton(self.widget)
        self.board_add_button.setStyleSheet("QPushButton {\n"
" border-radius: 5px;\n"
"background-position: center;\n"
"background-color: rgb(60, 60, 60);\n"
"color:rgb(200,200,200);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
" color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(35, 35, 35);\n"
"color: rgb(200, 200, 200);\n"
"}")
        self.board_add_button.setObjectName("board_add_button")
        self.horizontalLayout.addWidget(self.board_add_button)
        self.board_delete_button = QtWidgets.QPushButton(self.widget)
        self.board_delete_button.setObjectName("board_delete_button")
        self.horizontalLayout.addWidget(self.board_delete_button)
        self.trello_tree = QtWidgets.QTreeView(Tasks_Tab)
        self.trello_tree.setGeometry(QtCore.QRect(0, 50, 131, 421))
        self.trello_tree.setStyleSheet("QTreeView#treeView{border:0;\n"
"}")
        self.trello_tree.setObjectName("trello_tree")
        self.widget_2 = QtWidgets.QWidget(Tasks_Tab)
        self.widget_2.setGeometry(QtCore.QRect(420, 50, 271, 42))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.list_name_edit = QtWidgets.QLineEdit(self.widget_2)
        self.list_name_edit.setObjectName("list_name_edit")
        self.horizontalLayout_2.addWidget(self.list_name_edit)
        self.add_list_button = QtWidgets.QPushButton(self.widget_2)
        self.add_list_button.setObjectName("add_list_button")
        self.horizontalLayout_2.addWidget(self.add_list_button)
        self.list_delete_button = QtWidgets.QPushButton(self.widget_2)
        self.list_delete_button.setObjectName("list_delete_button")
        self.horizontalLayout_2.addWidget(self.list_delete_button)
        self.widget_3 = QtWidgets.QWidget(Tasks_Tab)
        self.widget_3.setGeometry(QtCore.QRect(140, 120, 551, 42))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.board_from_edit = QtWidgets.QLineEdit(self.widget_3)
        self.board_from_edit.setObjectName("board_from_edit")
        self.horizontalLayout_3.addWidget(self.board_from_edit)
        self.list_from_edit = QtWidgets.QLineEdit(self.widget_3)
        self.list_from_edit.setObjectName("list_from_edit")
        self.horizontalLayout_3.addWidget(self.list_from_edit)
        self.card_move_name_edit = QtWidgets.QLineEdit(self.widget_3)
        self.card_move_name_edit.setObjectName("card_move_name_edit")
        self.horizontalLayout_3.addWidget(self.card_move_name_edit)
        self.card_to_edit = QtWidgets.QLineEdit(self.widget_3)
        self.card_to_edit.setObjectName("card_to_edit")
        self.horizontalLayout_3.addWidget(self.card_to_edit)
        self.move_card_button = QtWidgets.QPushButton(self.widget_3)
        self.move_card_button.setObjectName("move_card_button")
        self.horizontalLayout_3.addWidget(self.move_card_button)
        self.edit_description_button = QtWidgets.QPushButton(Tasks_Tab)
        self.edit_description_button.setGeometry(QtCore.QRect(160, 390, 81, 24))
        self.edit_description_button.setObjectName("edit_description_button")
        self.delete_card_button = QtWidgets.QPushButton(Tasks_Tab)
        self.delete_card_button.setGeometry(QtCore.QRect(284, 390, 81, 24))
        self.delete_card_button.setObjectName("delete_card_button")
        self.card_add_board_edit = QtWidgets.QLineEdit(Tasks_Tab)
        self.card_add_board_edit.setGeometry(QtCore.QRect(440, 240, 113, 22))
        self.card_add_board_edit.setObjectName("card_add_board_edit")
        self.card_add_list_edit = QtWidgets.QLineEdit(Tasks_Tab)
        self.card_add_list_edit.setGeometry(QtCore.QRect(560, 240, 113, 22))
        self.card_add_list_edit.setObjectName("card_add_list_edit")
        self.card_add_description = QtWidgets.QPlainTextEdit(Tasks_Tab)
        self.card_add_description.setGeometry(QtCore.QRect(440, 280, 231, 101))
        self.card_add_description.setObjectName("card_add_description")
        self.create_card_button = QtWidgets.QPushButton(Tasks_Tab)
        self.create_card_button.setGeometry(QtCore.QRect(520, 390, 75, 24))
        self.create_card_button.setObjectName("create_card_button")
        self.plainTextEdit_3 = QtWidgets.QPlainTextEdit(Tasks_Tab)
        self.plainTextEdit_3.setGeometry(QtCore.QRect(150, 240, 231, 141))
        self.plainTextEdit_3.setObjectName("plainTextEdit_3")
        self.line = QtWidgets.QFrame(Tasks_Tab)
        self.line.setGeometry(QtCore.QRect(140, 180, 531, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.card_add_name_edit = QtWidgets.QLineEdit(Tasks_Tab)
        self.card_add_name_edit.setGeometry(QtCore.QRect(500, 210, 113, 22))
        self.card_add_name_edit.setObjectName("card_add_name_edit")

        self.retranslateUi(Tasks_Tab)
        QtCore.QMetaObject.connectSlotsByName(Tasks_Tab)

    def retranslateUi(self, Tasks_Tab):
        _translate = QtCore.QCoreApplication.translate
        Tasks_Tab.setWindowTitle(_translate("Tasks_Tab", "Tasks_Tab"))
        self.board_name_edit.setPlaceholderText(_translate("Tasks_Tab", "Name of board"))
        self.board_add_button.setText(_translate("Tasks_Tab", "Add Board"))
        self.board_delete_button.setText(_translate("Tasks_Tab", "Delete Board"))
        self.list_name_edit.setPlaceholderText(_translate("Tasks_Tab", "Name of list"))
        self.add_list_button.setText(_translate("Tasks_Tab", "Add List"))
        self.list_delete_button.setText(_translate("Tasks_Tab", "Delete List"))
        self.board_from_edit.setPlaceholderText(_translate("Tasks_Tab", "Board(From)"))
        self.list_from_edit.setPlaceholderText(_translate("Tasks_Tab", "List(From)"))
        self.card_move_name_edit.setPlaceholderText(_translate("Tasks_Tab", "Card"))
        self.card_to_edit.setPlaceholderText(_translate("Tasks_Tab", "List(To)"))
        self.move_card_button.setText(_translate("Tasks_Tab", "Move Card"))
        self.edit_description_button.setText(_translate("Tasks_Tab", "Edit Description"))
        self.delete_card_button.setText(_translate("Tasks_Tab", "Delete Card"))
        self.card_add_board_edit.setPlaceholderText(_translate("Tasks_Tab", "Board"))
        self.card_add_list_edit.setPlaceholderText(_translate("Tasks_Tab", "List"))
        self.card_add_description.setPlaceholderText(_translate("Tasks_Tab", "Description of card."))
        self.create_card_button.setText(_translate("Tasks_Tab", "Create Card"))
        self.plainTextEdit_3.setPlaceholderText(_translate("Tasks_Tab", "Description of selected card."))
        self.card_add_name_edit.setPlaceholderText(_translate("Tasks_Tab", "Name of card"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Tasks_Tab = QtWidgets.QWidget()
    ui = Ui_Tasks_Tab()
    ui.setupUi(Tasks_Tab)
    Tasks_Tab.show()
    sys.exit(app.exec_())
