# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Forums_Tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Forums_Tab(object):
    def setupUi(self, Forums_Tab):
        Forums_Tab.setObjectName("Forums_Tab")
        Forums_Tab.resize(700, 506)
        Forums_Tab.setMinimumSize(QtCore.QSize(700, 506))
        Forums_Tab.setMaximumSize(QtCore.QSize(700, 506))
        Forums_Tab.setStyleSheet("QWidget#Forums_Tab{background-color:rgb(100, 100, 100);}")
        self.listWidget = QtWidgets.QListWidget(Forums_Tab)
        self.listWidget.setGeometry(QtCore.QRect(0, 60, 151, 451))
        self.listWidget.setMinimumSize(QtCore.QSize(151, 451))
        self.listWidget.setStyleSheet("QListWidget{border:0;background-color:rgb(35,35,35);color:}")
        self.listWidget.setObjectName("listWidget")
        self.listWidget_2 = QtWidgets.QListWidget(Forums_Tab)
        self.listWidget_2.setGeometry(QtCore.QRect(150, 60, 541, 321))
        self.listWidget_2.setStyleSheet("QListWidget{\n"
"border:0;\n"
"background-color:rgb(200,200,200);\n"
"color:rgb(0,0,0);\n"
" border-radius: 5px;\n"
"}")
        self.listWidget_2.setObjectName("listWidget_2")
        self.textEdit = QtWidgets.QTextEdit(Forums_Tab)
        self.textEdit.setGeometry(QtCore.QRect(150, 390, 541, 51))
        self.textEdit.setStyleSheet("QTextEdit{\n"
"border-radius: 5px;\n"
"background-color:rgb(50,50,50);\n"
"color:rgb(255, 255, 255);\n"
"border:2;\n"
"}")
        self.textEdit.setObjectName("textEdit")
        self.widget = QtWidgets.QWidget(Forums_Tab)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 701, 511))
        self.widget.setStyleSheet("QWidget{background-color:rgb(35,35,35);}")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(150, 450, 551, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setMinimumSize(QtCore.QSize(169, 24))
        self.pushButton.setMaximumSize(QtCore.QSize(169, 24))
        self.pushButton.setStyleSheet("QPushButton {\n"
" border-radius: 5px;\n"
"background-position: center;\n"
"background-color: rgb(60, 60, 60);\n"
"color:rgb(200,200,200);\n"
"}\n"
"QPushButton:hover {\n"
"background-color: rgb(50, 50, 50);\n"
" color: rgb(200, 200, 200);\n"
"}\n"
"QPushButton:pressed {\n"
"background-color: rgb(35, 35, 35);\n"
"color: rgb(200, 200, 200);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.widget.raise_()
        self.listWidget.raise_()
        self.listWidget_2.raise_()
        self.textEdit.raise_()

        self.retranslateUi(Forums_Tab)
        QtCore.QMetaObject.connectSlotsByName(Forums_Tab)

    def retranslateUi(self, Forums_Tab):
        _translate = QtCore.QCoreApplication.translate
        Forums_Tab.setWindowTitle(_translate("Forums_Tab", "Forums_Tab"))
        self.pushButton.setText(_translate("Forums_Tab", "Send Message"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Forums_Tab = QtWidgets.QWidget()
    ui = Ui_Forums_Tab()
    ui.setupUi(Forums_Tab)
    Forums_Tab.show()
    sys.exit(app.exec_())
