# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Calendar_Tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Calendar_Tab(object):
    def setupUi(self, Calendar_Tab):
        Calendar_Tab.setObjectName("Calendar_Tab")
        Calendar_Tab.resize(800, 600)

        self.retranslateUi(Calendar_Tab)
        QtCore.QMetaObject.connectSlotsByName(Calendar_Tab)

    def retranslateUi(self, Calendar_Tab):
        _translate = QtCore.QCoreApplication.translate
        Calendar_Tab.setWindowTitle(_translate("Calendar_Tab", "Calendar_Tab"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calendar_Tab = QtWidgets.QWidget()
    ui = Ui_Calendar_Tab()
    ui.setupUi(Calendar_Tab)
    Calendar_Tab.show()
    sys.exit(app.exec_())
